developer:
  name: John Jayson A. Lopez
  contact:
    url: 'https://www.linkedin.com/in/johnjaysonlpz'
    email-address: johnjaysonlopez28@gmail.com
server:
  port: 8001
  contextPath: /api/v1/user-server
security:
  oauth2:
    client:
      id: project-web-application
      client-secret: project-web-application-secret
      resource-ids: user-resource
      access-token-uri: http://172.17.0.1:8000/api/v1/authorization-server/oauth/check_token
spring:
  application:
    name: '@project.name@'
    version: '@project.version@'
    description: '@project.description@'
  datasource:
    url: 'jdbc:postgresql://172.17.0.1:5432/postgres'
    username: postgres
    password: postgres
    platform: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: public
